[package]
name = "pusher"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
termios = "0.3.3"
libc = "0.2.125"
thiserror = "1.0.31"
anyhow = "1.0.57"
